package com.supretest.commons.constants;

public enum ScheduleGroup {
    API_TEST, PERFORMANCE_TEST, API_SCENARIO_TEST, TEST_PLAN_TEST, SWAGGER_IMPORT, ISSUE_SYNC,
    SCHEDULE_SEND_REPORT, CLEAN_UP_REPORT, ZENDAO_SYNC, PROJECT_PLAN_PROGRESS, UI_SCENARIO_TEST
}
